[package]
name = "json2ch"
version = "0.1.0"
edition = "2021"

[lib]
name = "json2ch"
crate-type = ["cdylib", "rlib"]

[dependencies]
clickhouse_rowbinary = "0.1.0"
pyo3 = { version = "0.25", features = ["abi3-py39"] }
rsonpath-lib = "0.10.1"
rsonpath-syntax = "0.4.2"
serde_json = { version = "1", features = ["raw_value"] }
thiserror = "2"

[features]
extension-module = ["pyo3/extension-module"]
default = []
